In [1]:
import numpy as np

In [2]:
np.array([1, 2, 3])

array([1, 2, 3])

In [3]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.linspace(0, 11, 11)

array([ 0. ,  1.1,  2.2,  3.3,  4.4,  5.5,  6.6,  7.7,  8.8,  9.9, 11. ])

In [9]:
np.random.randint(low=0, high=100, size=(3, 3))

array([[29, 70, 54],
       [67, 74,  5],
       [67, 13, 32]])

In [10]:
np.random.normal(loc=0.0, scale=1.0, size=(3, 3))

array([[-1.53099809,  0.28393968, -2.47979139],
       [ 0.5757081 , -1.83812573,  1.06703293],
       [ 0.46080152,  0.33566976, -0.79168227]])

In [11]:
np.random.seed(101)
arr = np.random.randint(0, 100, 10)
print(arr)

[95 11 81 70 63 87 75  9 77 40]


In [12]:
arr.max()

95

In [13]:
arr.min()

9

In [14]:
arr.mean()

60.8

In [15]:
arr.argmax()

0

In [16]:
arr.reshape(2, 5)

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [17]:
arr.reshape(2, -1)

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [18]:
mat = np.arange(0, 100).reshape(10, 10)

In [19]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [20]:
mat[4][3]

43

In [21]:
mat[1:3, 1:3]

array([[11, 12],
       [21, 22]])

In [22]:
mat > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [23]:
mat[mat > 50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

### Broadcasting
The term broadcasting describes how numpy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes.
— [Broadcasting](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.broadcasting.html), SciPy.org

When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing dimensions, and works its way forward. Two dimensions are compatible when

  - they are equal, or
  - one of them is 1


In [2]:
np.array([1, 2, 3]) + 2

array([3, 4, 5])

In [5]:
np.array([[1, 2, 3], [1, 2, 3]]) + np.array([1, 2, 3])

array([[2, 4, 6],
       [2, 4, 6]])

In [8]:
A = np.random.randn(8, 1, 6, 1)
B = np.random.randn(8, 5, 1, 5)
C = A + B
print(C.shape)

(8, 5, 6, 5)


In [9]:
A = np.random.randn(15, 3, 5)
B = np.random.randn(3, 5)
C = A * B
print(C.shape)

(15, 3, 5)


In [10]:
A = np.random.randn(15, 3, 5)
B = np.random.randn(3, 1)
C = A * B
print(C.shape)

(15, 3, 5)
